# 서버 정보
name: excitingirc
info: asset/info.txt # 서버 정보
motd: asset/motd.txt # 오늘의 문구 (Message Of The Day)

address: 0.0.0.0

# 관리자 정보
oper_user: admin # 관리자 계정 이름
oper_password: admin # 관리자 계정 비밀번호

# 서버 설정
max_clients: 5000 # 최대 접속자 수
ping: 60 # 핑 주기
timeout: 120 # 접속 시간 제한
