name: project board
on:
  issues:
    types: [opened, reopened, closed, assigned]

  pull_request:
    types: [opened, reopened, review_requested, closed]

env:
  PROJECT_ID: 1
  triage: üóÉÔ∏è Triage
  todo: üí° Todo
  in_progress: üöß In Progress
  done: ‚úÖ Done

  event_name: ${{ github.event_name }}
  event_action: ${{ github.event.action }}
  node_issue: ${{ github.event.issue.node_id }}
  node_pr: ${{ github.event.pull_request.node_id }}

jobs:
  move-card:
    runs-on: ubuntu-latest
    steps:
      - name: figure type of card
        id: figure
        run: |
          case $event_name in
            issues)
              NODE="$node_issue"
              case $event_action in
                opened | reopened | review_requested | unassigned) TO="$triage";;
                assigned) TO="$todo";;
                closed) TO="$done";;
              esac
            ;;
            pull_request)
              NODE="$node_pr"
              case $event_action in
                opened | reopened | review_requested) TO="$in_progress";;
                closed) TO="$done";;
              esac
            ;;
          esac
          echo "will move to $TO using node: $NODE"
          echo "::set-output name=moveto::$TO"
          echo "::set-output name=node_id::$NODE"

      - name: move card to ${{ steps.figure.outputs.moveto }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: ${{ github.repository_owner }}
          project_id: ${{ env.PROJECT_ID }}
          resource_node_id: ${{ steps.figure.outputs.node_id }}
          status_value: ${{ steps.figure.outputs.moveto }} # Target status
